[env:waveshare_esp32s3_relay]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
upload_speed = 460800

lib_deps =
    256dpi/MQTT@^2.5.1
    emelianov/modbus-esp8266@^4.1.0

build_flags =
    -DBOARD_HAS_PSRAM

[env:waveshare_esp32s3_relay_debug]
extends = waveshare_esp32s3_relay
build_type = debug
build_flags =
    -DBOARD_HAS_PSRAM
    -D DEBUG_ESP_PORT=Serial
    -D CORE_DEBUG_LEVEL=5
